---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backup-store-creds
  namespace: portfolio
spec:
  encryptedData:
    ACCESS_KEY: AgA53ZJoshFgco2aHZH/nXLzJUgCm7/7WHKtl9lnlIXYeRoy7y/kM7Kpz4a8H6T9BpVKkfwAAlOSxAJHav9KQC7DIZp91Ez9xTMYyXygJWNpUPykp3xEaIWUFzzWyYazBCw25J6rRuEHs+8B/gBUc+mNFzqphch133LGrFc2QmC5aZd1njhifyjzaNyL0w3bH4HYXxFdOfAfA1qwYEWL2rgt5Pw8YLiMpd2LThyJixi4trUrzVUo2t//naYMJnyxTrY0nOF39K8lwdTOFvB0IrvzsPUxO/JxIwGnp93cOGt4yAkLcjTIjO6nds8jgDSzGbCIUxuVB6ROczCYxevtzmrQwYYHO8noZ4FYLThWxIDHI0mri7nAqcfONgYipUVK7f6wYBnXA7+eZV6S59mZrF/RJqMxFTykmtMPLyVa+ga/mV68nKnHcLtsXLCfKaJdn7y5VmEN4MZeUd4B/TM93Qzn4ygT25RNxp9VDrLFxcOWYGdTrEi7paLWPBmZm2LDUU4r25A5iSZVjMFWUTm61EurGR0rhSqaLE0pbs9iWUjbINeqo4p2gHeA8UsPwfFnpuaBPFow/8RA7SH9vgTqqYPgO/uWcy17g3cLkZMS1yFK5GIcfavXfC5F/mXNxTaMAjjzpkpdV4ZV3YxisRVFmKkNqbrTojjc3LffrJ/pjQMK+/zQa0o7EYhMnSXPBJigHMDXgA46vVXstfc2oldYfvEhhYfWYMNKCgJwfw==
    SECRET_KEY: AgBvSYHZj2j6VVw3kbnfOK83G/DNdGRb9+w5F1NN6QuL+1mDKRVGPhceca0Q2hdfcA/kr5rHYtRyxSgXFeC+o4u7Feka67akG8b0OE80ZXRZJKMt2G/dSMMd3ZaY3+ANCtfQdgfSk1bwYIovgXm/KiqeGIRKNVRqGp7gTaDii+BCQYvSbC/D63hg72MUa3Dk7hrIzHKYEsGpQttOnfH6QNYbNcsNHN0idM1lv4qpLmlhp5jwd/EHAF8FLbkPliy1LLkuE84X5gxpoSIzvcflncK54yDDS6NYDNSpzAKvRcLxBae7XZqdDOEAOVr6BrWSYa+qVw1KsiyXAa7Yegsiz2SDwsXjnwJy0VDxfzqxyzZ4XV+672GVPZ28BN9aw1xDEH4Z3kYQbAxOFe2ny4rcEh7Z76zzXEyniSiRe0R7CZfSLOIB17ZPUMxHGgQq9oteb3oV/rZq42+lG/G9hZ+nhUrxnIqLh/fkstyhKZMmcr8noTlEJGitueA9osXmAdF4yBeq/XFs9fBUj41O7SLiYv4aWdzZJCkeKFMFV/RiUvoQlrItPcaD4SnNIusBSDZT23AQcz8AIz7uNqbfOtVT0gYe32dN2j81p68+7/gpWNHmIHdjN1rl7zCslvIL7wh4RXM1rXa+9K1MD+kb3gFmw5keStZzfxKGCeB12G0jI/em4AK4l+fhKj6WfhQCNyigz+FMs7zULJZckAumYOUQ1D9Jr4/6qcCVVtZK89QKzcAdvmf3NenQhlqxxqRJXTkkM4lnrupIWedKLRDcLVzB01Zp
  template:
    metadata:
      creationTimestamp: null
      name: backup-store-creds
      namespace: portfolio
