---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgBVrWDbh2xIoqe/bAyAnjVQdvAdysCZVCY7JG98Z2igh5CBnZF/Age4xmPGEz9GcRdqR6HEkEj3RtF5jwMCuknO3qn2Wd7RH9nOk7uqxMKZl69Xs5U1+7qi77I/WRjCvV9K3B8LnxDDqlXmdexZoYTGJckVvrwOllmy+HcppXQzjeI69g44RWnieJMsNeKroRxjk/XUpMTJl++Z7rvLdRmKEkbemqDs5n/VetaGrrFZNlXfgE3DCxlLP274fLfOXoKXs/l4QV+FDpMlVRoIbcr5xN/tlUOdMrM8Jd9zrCNOslsTKjFcilTanAD/2VsZ3QGU2iQftf/McmemowCHEMBJMIYBVgapMrtd6cnuDQgR5pP1JrcNT54eX8tU4UPRjHz9VRrzYPlFKb9ti+RX9FrvCjBAf8f5b+w3wwVTu7CoS3T4rYggFuPydPN8RgWgk67gD5nUW/rkA/vGFZRcsIM+9ozRmGYVS32UzsM4JqZyyomawRoA6NymeE62qgbWSgH3HecWFLV3NNghN+ezISI6kt/Atdcqp0LoiORdmSD4drvTmfOsF7Voc9Km7Secr8zvfuilciiBXiYOHO5QfA810tntMxz10sGDra7tVjoJ5gBpn1JcT5dT32jvsZC+vM/HpU3BeJuCyy46c/bCMFYjaV+NC/WMzTPNet3bJ0I93S9GVYPM+ekPgQ9yIUTCbUu7Ny/SS+9V8284OZA8OsJ1HcGmXvGw+kjZZYjwMUhLwMYAclrw8PW95Ui9OT0qrBIXS4kZ5Q==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: cert-manager
