---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-api-token
  namespace: kube-system
spec:
  encryptedData:
    api-token: AgA5cAuv2DxjTGgzkSaom853CA+Q6Oa527CRE5xIEK7j1SGWJ+uao7TqPMgT2TbCadqHLiHyiUq2nTpMQA8iJOZxZUvgK/DvKae5YW0FiXaLS0VlKx5k7Arl6ANDvqeGXtflo9j+7zFawqPz37yqWzXkDLtjQk+D9o098u1yS+rbG0TRtUIKM6v4ykdDVpEPx+2BtgiqXANQkfPx3cjKD58tqJ4qYMVpEK2Pr1svPOR6cST9/J9X2HAVu6C8LhLLfqp2j9Te8EMxHgmk6CfW5btjO6IFXFe3p/YAMabqt3a1bcbledQuHw37tN1uZfbhjw/cbAOCXjQ0qOI0ZEaLl+KhZ0lK/EvE1SheKCyNEFP4xq1f4FCsj1NLZAqy7fsK7qZ/EZY3owXdeCtTjPfby5859xkH6hNw65xpMIk3y0788wZRDzg58X3LQ46OQJuDSoYlUcrJ9yoYlM4OAvyVjVPC6djjV0bYKpYl7ysPdMuMwd+Yo26E665ZOYrT5Gy/6ntBEHACzKS7WxQ6fs6zTUz0btxt8AtfTY9uaKLz/T9xdyhhM04gn8tN8X0Xc90cr4UTA1elp6mI5rBDmvUENkvx0D4LtpdWCkyKvqRnOAZn5zf866RW5U/BmsLRDdJK9MuJqk+MbqQyt7WT9Mr8KdslekFNEjd0A2acpVceLehdqv9Z1hM09Id2Cb7ErJ8MUZphXjvT0jmmnKJfQXrRAkpQAnr7pKjwg7B7eE03XY4gTFQ+Ek4LhJPl3frxgwmSZnRCJY1yJw==
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-api-token
      namespace: kube-system
