prometheus-node-exporter:
  extraArgs:
  - --collector.hwmon
  - --collector.thermal_zone
  - --collector.rapl
  securityContext:
    readOnlyRootFilesystem: true
    runAsNonRoot: false
    runAsUser: 0
