---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: garage-secrets
  namespace: obsync
spec:
  encryptedData:
    admin-token: AgBJuVgJJ+wEr3jeOsAGxAuMzJPW43JCylFwqFYFtEet0HSs6UJTmuTG/nw6tvoHVVnZk10y36i8bhduKC46EQQk0GEvTUWtWDatfGDlOtg6jAFUotEarKWWigT3pPaA3UWmIDCLrCb2AJHclo4S2ZeAXrBsl8xNVm2CRstyIrF2taW33BC80Px5b9oKAsTbw4nTQ9UyO6dsbEH/5Ye31ITT0nQeYlLT/sjd4cgu8oegaSfrFMj0vfgtDjfaTBab8emqZJqS4ZAQajc7dW3P8hrDrr5zyxRaQnUchXyojsK/80pvesU1PzaOShX/szDfv+NsFVTTzYo/2uFogfVGpCUngg/CE5CgaHQ819dcUGtd8P+1Nw8mtkkQI1YDPlsQ8ypeEQ+rS16RCwQ5PWe5kktzk6laOcM27oM39Mop9QP75VFXOBr5I+3XXn8lJENZ2JRNm63W7IN7MfZL4L+2LhNjaa7b03jrqsc93xc2s0aoqXzUGOkxnFEBQ6fqFRQ6eTa6mT+2LE7un6vWBuaTJd6e6etmF13Fcwuymt6yCAbFYcHvKNEObhfPHg1WMlhqtJum85sO2N8xPoxZ5Xqk6FEn86xzZ2S+++bSaBHbEUuq3BG0jc8R1K2DQZXNs2LJik3wa9e29n3knQvD+DSK+2Wrr6+ryUuHm/aOIuwDfPJKo6EWdRoLmmrFb3z4vbQd+e40C4wBrIKKvDl59rctnKtQ1xxWVblQFW3O7Mwp4LN6Aua2Qohg3GAHDOjwnw==
    rpc-secret: AgBiGuUy4xjMeAi46qUU/weqN69Jc/RNVF+Qnz+XJPqBOlvJ+UXlkOG8gn2/g++7t4SGohHHIwQUanCoDC44kitiuf0WjtscYHbpRVgurqpvyTKQRIFiqGeYavYOeuXelXn2yEJbYrX/JHB56eZdIimOKnIWg2YiIJAuZ2elhzA0hs1t/Sp6Wb4eIVQt8uzLkhcb+GWADbwepJYIoQrCgNNqYA+5jBTaxtls9kJ1uS8nS38PrPPq2jnYSfoL6PvYFQvA9ts61UKg8/b0ig383hVs8Rmbv5jXiO9gyT4IBm9Ib1m0meCqxDKL0tIDnN5TNzk4/gTurSrJIYHT+IYJ4XjH1j1pDdUCj800vVs+g0qmFvuDmdbUn7pe9xNjNx5DKd/IhS5n/G7QJd1N3T7Of6fWR4JmLtNnbes4oItdMxvArQDj1J1IZiI0BHYCiHTruYnNcmXBee4A/ANendB87gMVfbqADN823dMmL8HLPCAhvGCpZ3Sxs1cj2O8cKpUndj7F53Z2LPSOvAu5e9ovHAOUth2FRIblj1YHLbvznDdD7+9B6PDUcth8FpVj3iOSYKMBepPEhMPSECmS7Av8sAzqO9r/EW3x/R/6WvrAYmlJO2ISE58zQV3pNCSmjTQUkMBSvR5ACR5moHYv6rXA6v0+Zck7i5zeWT2ZXkfYByBcPu9bOO8xsQBhWiYLAFKmGZZxlOVkafZu2wqczzjb+lxxjKHeTJOQW7bH7D2AbZD3s8BSdbVo3wyuFj7IpBO3lbdRsqZAfPlscaBYXZ8MNWH4
  template:
    metadata:
      creationTimestamp: null
      name: garage-secrets
      namespace: obsync
