apiVersion: batch/v1
kind: Job
metadata:
  name: portfolio-backend-dev-migrate
  namespace: portfolio-dev
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  backoffLimit: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: portfolio-backend-dev-migrate
    spec:
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: migrate
          image: ghcr.io/home-compute-cluster/portfolio-backend-dev:git-sha
          command:
            - /migrate
          args:
            - -dir
            - /migrations
          envFrom:
            - configMapRef:
                name: portfolio-backend-dev
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: portfolio-db-dev-app
                  key: uri
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true