---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: portfolio-backend-dev
  namespace: portfolio-dev
spec:
  encryptedData:
    VISITOR_HMAC_KEY: AgAlm2DAMiaKOrFT1l7g/qfF813GIzSP7AGU3Nn1g8H/QtzJGc3OwJmHN+LQMWJBPsB5kd1Wdxm96ThTjeUwNL227MkW3iLx6z0MziUs5lhaE1TKpGbO//+nnuqwokx+jdthXqGlc8v5lf9VYpDc9Q/zIC05RC8G9H8DADrN85ZPnFbq057CDKLgTMt38z9s3fID6+9L43PrsOmqi/ITW+3ROfUJTv3gnCMVE6tI01d3lGlMUahCtYJaLO5koqciarCyJBW6kK2D/+gsoxlNISdlVBIVM5HAgmZJnaWA/uxW3CllXhRtY5jY3YDf7PySVbfyc8i/CU0uWXVDcI9thNSw7yqSq+wSITr3c++oNvIUXGradHjDw9CTFn771+xoTHnvtuWqzycP4A8xk73YKzr1O+eU/1Tpy0vKYmyT0uWZHU2H/uJITTXiHld0OVEgBh22U5evRZIvagvJMxVPsuIxsmwLRlUIFvL4HL9VHDGv2R9/Ad6nLCzTvxY6phqKqNrzNhra7dRa0A+c3L+5JVUFItBWZnh6Sd+PlywOIXmnP5P6oKuh2QkJ5ALU6dMuU4oTUu1WVS97NWMPZG9HVlgQGX1UgiS54wyF6cP70doSpqxqU+XE1vAU+u8NaSac14eCSFAsJkd9PyrxiNL4Bl+NzwcUrpIlJ3GuDXoSkrZxtj/tgGwb5ExpM5dgRHVBosNVojdHj0OhMHokPkMnk8AwFCIvARSAr6HgXAXC+LTiluJaXQbE7KFuk5TXvw==
  template:
    metadata:
      creationTimestamp: null
      name: portfolio-backend-dev
      namespace: portfolio-dev
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
