---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: portfolio-backend
  namespace: portfolio
spec:
  encryptedData:
    VISITOR_HMAC_KEY: AgC1XNMmHjr6uertK8knYJlx0Rf3V2wGlnj3huEAvh1ao+5eLwwy4ARUKRyCIZSLcbLwJXd9rFwYVPD05lrTnglv6sRG+nnX0K8E+3BsNXk4egqRIEdu3MQM/7BejmqA0l2ufLRRtBkC1yEbsFBPsAjSFiYkl6sEuJivRO3MeoX7RL4pOlT7JXDn8KK25kQNN/JvJLPQY/78XbfNgIcyjk0MeFGtn7bYeX6wZueR3ixUtKIYnI2aX1vxTFZ3DhWF8D+tD75us6rGtEoftXzb0c5E/TX0p0ciPFht4PqK5vWFK8wbc6xdOQ4AtqqiRvLFD33q5U6YMqC5qhlCmkZfKh5F0r/joF0UjOl5MsYk6EowtxFN6bqbRAYgokJzmn/c/2E+aZrxLRAbxRzufPr48JhYrLetpPRhntnnUNlt0L4qJNoLfy6UQxV3omFqyMzwNagWnQ4pR7lJfuuRFY53nCbd03KvBuMPgb/PWdOzAk1n6z1KNDS32VljFAhDhkEBFFecTghp7FyXpTfwYEpUNjmqDI3dqYJS5EuhuEAR/sYdgnF0ndFsQcjjBG8WpEw+Fgl7eJ+MFWiP129zuWrN6V8ovLy5+uWhxIi5O+QTTRnSLm3wUCyoYbbHuwrzJ5jreOtOsVFojTUvd8Ndzy64kZTIv5fCmT1HVleFRyq0i7ijeCJ0bKk+VnCR/sCUEpK82xbMeCe83f1iaCVewvGAmXTDNJzymrHiSYIZrU26mhsMSMOEfZfKUVfVAY1/OCtoLKKOtWfb9hvCu1ryXaAxVpBI
  template:
    metadata:
      creationTimestamp: null
      name: portfolio-backend
      namespace: portfolio
      annotations:
        argocd.argoproj.io/sync-wave: "-2"
