apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx
resources:
  - deployment.yaml
  - service.yaml
images:
  - name: ghcr.io/barneyLaw/nginx-app
    newTag: latest   # CI overwrites this line via `kustomize edit set image`