apiVersion: v1
kind: Service
metadata:
  name: penny-dev-db-lb
  namespace: penny-dev
  annotations:
    svccontroller.k3s.cattle.io/lbpool: deus
spec:
  type: LoadBalancer
  selector:
    cnpg.io/cluster: penny-dev-db
    cnpg.io/instanceRole: primary
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
  