---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: penny-dev-db-app
  namespace: penny-dev
spec:
  encryptedData:
    password: AgATfsbWe84P+Om1yoh2ulPk13LQFUjnRpn9YrIKpak5GZ2cJzzEGTKV6jrmTKZyfPcrboZ2rGj3Elw95jpDMtIIXXdrnKf+musZRhS+jJOObaBf4T73Wd81aoGXD6mbrJce4pIIlj2Cf55y7+UnB1NHq01ZjTG3QqtNGMHDL1JEIC1PYF4lnJ61OOvMRItV2U5sW3j6GC/cVFRlcnpdAnyW6b3hEI1Os5Xt/+kKcONUuor20LGgDkVwZY3fUg2AKq1n9bhFL/gMcG+PHT6wvvF0+fGkaxk4ykgGeAGdezAi14ByXO7QX59S5EZy5/i7HyN7PhBhQi4YU+kteuXOVhRl1mZcbHnh8BqO/90BgmOQyJF980lqT6Oogl/0QXvo8MstIxcmLCsn6tcavOym7ytj496J+S/21vK2McyWL6Y69bwm+/5PoIn6O+T8ZXt70KMEog2BXX7QKvE4jyxeho0kyee/wVJI1zZWJl708580x3yaAfiAH2LjAoe54RcmeILwb1APheuOnvkS5vsb4Wb+FDDT9sR7EG1FruRalospv8RYzACptnMhCb9pBQcHWoCXXoI8nw20tHb3/bMuorgbeW3pFghdf7njr2BJBO7c88Fe46B2H2lIbEqdq/fe77tsuVH8LdxnIh7jfUm3o1fKgPtfyUYuVQpGqgaZiwjxhN5O+eC54T4tsxDWcVcceQ/UxNML9E0Gr0c7xtJDzMPwMKKlo3dTzZpzJTUnpizuHg==
    username: AgBbnohv8GbfIj4kVyQLe/hl6l/dQSYT3rUcTBCcH+jXwal2ef6Q3Je3FSl5TNUl9ozP/Amns+fVUg5TJU4YVtaZRtgOQnEHcqgW0fgpv3KyabmyjpaNZ8T1oNssVefaeHYvpOma/xvBI+hPEmlYqAA3mWIQjOAw9zGmxMEiEM1CW/kSRzChHbFtTGPjF0fhDqzdGQL2l6f4fc2E9qJJISF+QljUU4CvhWcllSBXYDRH2y+iU7mxLVgQ6PaQccQrS8kZSvrD6J0Q93iqevLZbERQhZ96MAgvDUZqiZPFEs0Mt7sVW4xL5mh7wU7NT6yvdp8MxLYnvFePWAenaUX6pKk5WTx4udx2RnKqDhpDO0+ZcgrjpEC4pydCjazUTrN3/9qfmV383U6xeIzvM4smFWmbJ9foEEgR6V0SbmU65kLk6gtDGhYikI3qkQDQHzZt+e+h5GOAUHOzb9Xygku1YKJ6eTLuEv7cN9Ne/6i+2VsWlRidBzfklk2UvFfulsCM2dfJTRNtRV9ajG7B6zzYP/szK3M4RZav+MSfiM6beNb03cn5JF55LT8+IyRTt0Ow+b1yh1eMaBfIh0auGz6CH/TRU0qxLHE7NGvJosAXdh0F7ytskcnWrznhbpXxmTQLZ2+dhjhPgm7pbL/DjCC+BVE4xGx0UWJojtW7D53jo62ao4sJXMaXnpVH7tEx0boLW9FjMCuomA==
  template:
    metadata:
      creationTimestamp: null
      name: penny-dev-db-app
      namespace: penny-dev
    type: kubernetes.io/basic-auth