apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: adaptsg
  namespace: argocd
spec:
  description: AdaptSG development and test environments
  sourceRepos:
    - https://github.com/BarneyLaw/homelab-cicd-config.git
  destinations:
    - namespace: adaptsg-dev
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: ""
      kind: PersistentVolumeClaim
    - group: ""
      kind: Service
    - group: apps
      kind: Deployment
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: traefik.io
      kind: IngressRoute
  orphanedResources:
    warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: adaptsg-dev
  namespace: argocd
spec:
  project: adaptsg
  source:
    repoURL: https://github.com/BarneyLaw/homelab-cicd-config.git
    targetRevision: main
    path: apps/adaptsg-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: adaptsg-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
