apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cnpg
  namespace: argocd
spec:
  project: default
  source:
    - repoURL: https://cloudnative-pg.github.io/charts
      chart: cloudnative-pg
      targetRevision: 0.23.x   # pin to current stable
      helm:
        releaseName: cnpg
        values: |
          nodeSelector:
            kubernetes.io/hostname: deus
          monitoring:
            podMonitorEnabled: true
            podMonitorAdditionalLabels:
              release: kube-prom

    - repoURL: https://github.com/BarneyLaw/homelab-cicd-config.git
      targetRevision: main
      path: apps/cnpg-extras
    
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true