apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: code-server
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/BarneyLaw/homelab-cicd-config.git
    targetRevision: master
    path: apps/code-server-app
  destination:
    server: https://kubernetes.default.svc
    namespace: code-server
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true