---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-notify
  namespace: monitoring
spec:
  encryptedData:
    discord-url: AgDTFtv6+8G/ZV0K2f4mcVzDSGmyLlS2xOPHLGn7nsYm+/KtBMqeSuWljlCFdCqJn/aFs45spEBDewwxotyeV59/ttL4pNp6+NLNfLUlyPWfVKD8b8ScabiA07fgxin86MunhIfiUTfPDZZbpNemmPvJvXB4wz0BtXwP8/SRcDRAnRHtScEDuW+BnJZKabJc6NQB586B6GbEd9V+hgU6vWmewm4zdqK9EaJ80dykSfbtkaoSmkwO6zFzpLsbGBnSp8ZNuJ5FbKI3joHeCUsxRuFvTYXEl2auNVrlofXhtO6U9tAibMGcT3a4v9m1pT/BF93eEPweGd9WgVoEyEG0473/kwpNWPB9hJbH1vo6Hb1JHQC7cyn7W7q1F1QdNcFSIGci0uSfRfY0kbIMta+HmdZkgj+dOPM9CNXgPCFiJfOXaMZ7b64ddirmePXh3p8/decRPekuqQZadxkb1GGokRCOHqlppB/maVW7EYw9DJwoxh/N/G8YzYSG4+mRZwiSnHNtCtjbFBqpSnPCLCWQP7TLvg6beyVIaEoodZaOOf3tNamYIRtP9PKhYyOaw3gnJ1U5NqgftdHDAKPKHQBByKW85t5tYgILgjuXgHvnNI8rILXrZKim78pTvwenMvi7G5cPzFx/z3tkMJD8v8zEyFLIISAKlAyNwJPhPGw697to97cF4cx6nqOPt+45HcM+OEwprkFGFVR2BP75K45AP8UPnQGcDlLaEbTjZu7hOmffYm98QKWjtyxtjiP6kczvCZFY1AsxHYPTlvRIIHh7019ponXebn+cy9YpPlm45ffBnnen/YKt1kufFqJNUMlEjRZpTNsgY95iO3xHJ3aQ4bCn5QsffqN60cMT
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-notify
      namespace: monitoring
