apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCJIq9CiRZv9PBrdesyY1OsJok4P7aDuBwzH6JjHdjebeDbV+WpCxpBCXs5VOzZuObk9QPXcjgo6y55ELKExVhYH/RZ/sQlpu7glA9IvYDk0yJlOGOxg7hKSDfbKWlV6L85hnlsaENyEcb3sIQ/HozYdi3eXLSGVuBdBqgtCABWZJDyJyarp9CO6VBsLnjJcSmiwCUPVuXjQqPYGWq3SpDgZQEGOZtae7/EkrFSLTnXDrxrBnbNXYrGVaEja9Zy7RtrLLTZ+nZqGXCq1Ngc3R0br4x0t4xzqzWrtVB1wSikoYSEbpLhRx0mraqgMP6GVQkCa6dP0OB+8MV63aCpITAwodKYH9ks3O3tGOVrAhK1fmbe1Kg1DbKN894g7sH7Q7GSqtHo2eXoZGrj7xAlGXbw4cEbSjNujSf32AG37ciU8h9P+wxPoYK/TbOV/7YO1xr3k7F5oLL1eDY+YaMg2mUvCFdYFH537dqAzKJnDpl3VE9AaxlfPfxtE/xbqAqXhReAfbf90o0T4fKtMZWB8FynOI1/BZkWrghUECMUYySWzQJ/65t7DaStESeIYJnIL2TuMEUXkWN8SV3D7qN4/aOdCyc0okh60yOwPztL81BVYIYIiaa33zk9XQp3ZVNDACVLjKriTS5x+5hABXwY4nmRrQK9V3PGhhaRwOuZwgug/HI/KyBnJngIE2W0uJG9h+ZarVkU816aOdHxvPdaFOWg33KeHTzmu2t7ZvckUvTHAaqqsjXkfFeM
    admin-user: AgCX75HoPD0ETryL8RzoshF0Q6sMZKAHpAA1koJmfUlbasqshWL83/1cdMpqOGH0AokIUiz13Y1xQyGmvAfes5NEzJyb0UXaBi4qyWKSCglwWfniazQp23/th98AFjz2IRKXkSiqOjEeLrP5YXCHaHPn2SsYkXIHwDhPoizo4vqK9tUSLWc/qRWdXl1BHq9PuoxSBL0TZW5hM+YZAc0Pcw4+pOwzR/EbeiVfZORNVxUoJkA2ty076xkej9FwNWaitoxmBCJB0ZQJwNLle4RdddkC5hSxomfKlBkbTvx/9cGKM2WDcw0CGdympUoHYbja7jvNZFx/n0hcTI0J572y0EcOwlB38Xb/JimeusWM7/qSGiImswZotKgDUQqllLI2/lcEr5VlbGNUwqDCpAOhb6x3/+U5PCIs/nnpUzA9kyYXbv/5Hyytl3jVyxx/QxzTYVSSGC58BogBXJdndY5/+ldJZfC5OFWw3ve2LYJolzbpQ77Yi/COGBiCSgHK0D3s+UcdT/9gdLJqJX0wVVVLUGzdPy7bNUCOI78/qTOtvsm14IeO6pOjVuR/XvowlgY6+3ROfQfll8nNm3arYma2CWn+zJmqSgUjMPtys4AjHDL3qxoc0gsCtwVw8OlKN6CtmV9QzTCujuxfL1fhaaqVaMRCYu0RqiVOPAoYlvKQoQl23hjchWk2Yrc/NWu8R8FbYIOQTBFO7g==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: monitoring