---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgAd4oGKynmd0uBYuOUmTIIv7+H8fBxNDL6xBCWlTtmdql110J3YDktPir5Sie6Np0L0UsRCPDHbrwJPKexj5d0/ZjPNvK+f+meu6+wJaiFJXojbnIK/wRtoC3Hip9ICRv0Gs3p/x2Djz3mU6SoR7Nhk/WCvgF697nFIAHDvX9Qg/awb4EeNdTKfWZjFDzkiQXMy7d0GlCq4POYCvrs+fFv4/508/folv7ooL9NCH/5M6p2NLAZ6TqeGHMmnC4T5TW1+Q0G2hvUNEuS6fbtookU/srSWvkP1ILC7xPKMj1CWaDynJTbLE64KRguziKNgpIWfsbJwEkSFCU1M8wjT1KUh4z/8mnY2LLt3gfy0Dh1jO3TXRK8QXR6hhE3woiyTYkUrQGK83Z0gI0I0BrESWItfAAewRGPIDUZIbU0MN3k3St1AbjPyFLbT8RPOHTVgUegMNM5j0XTC1qb10a7v5UOSa+eht25foOjfyWe3L11i21IS3Vft44L/cv+ZxkQsnU6tmsIOnLW5zXXK8HO3TJLzI1Kx3YURpGQPlGiYDrN8de9XeHK/RAmqLXre3d07bklLN3N13nQW3mI/eIDfJ6Oa3Wl5eBeqicLv7FPJXANY4gg6zeGKJBkRoI5ZE9niF+C6YFwJMuMntH3gekRS483yI//1lBcaRVAjYSOdpuetWu8MS1oJnvKIetP4I0gNM4GlHg115jStaHbqs3SPTwlRckBQ+HoUBwmTXHYZf8xbc4kiN0IFsTTxvof/e1iThua5IzL2nGb6NZzS0dnbiqkAQAVGTK+MrEAYGOQBiSIUPX29eouB70hnUAYzu/Poe5URbLIdUebGC3XjQCO+ZHR4AhbbM9sTs+53k4jijPlQlYUEeKqSMbyaP+LVBRSrqurzpE5mZqw4iX6H/YQ/JTxkNjt+USPpUOCvoTiNK5kw62NPC1B+/ewo
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-token
      namespace: cloudflared
