---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgA0YHIKtKftHGosR7x66/W45PionTG5KqLoSJh9LymJc/maFc27yS8EqojqkA4pLfQ2zRMvzjxr1LVQd/IRetE9f/KKGLLnVch3ovr8DaXDUYjhvyHicwVydn0kDiyfiM+LsEbrxYJ/9/v5xBhTRLG5DtX+0yRN5wWofhJbCRJXRDJvjwPGBpCvS6Xr7svLE9m2MdQDwz4094ODhj+WfnekQ0MNACzoOojGHAmuX9uadG+3KgAZXPvZ3LAgdXyFa9u5/d6ciTEPSTI2JPRgU4uqm1Exjy6z4H93Ab5o6lFAgajKf/hrLrjKiMMS3OfLPTg570IGBOsw+MhZhLl62D0nqus1bB8RIJzyZTDF6gIWCTVFyYSHCcreJsVAz/uJXM9fIT+jKwCg0iwfQWvE6xGQEUYXnBeO2GB3lxwwDIat2X7NxwmGc+2QBFRPiGVS9Nx372kdAF45/fyANOb9zxaUu5TI5+opJ7kvmo310xZ8Kgr7lznj5GU4xxNSVatx1VP/0vVjvJZilaLm8sB4doSuSMQsdCGy/TPMseLS3njorDhm2sOxf+m++GGDerlf6aOPhhczAr7zr2A+TvF9TCClbubrCCoIbNH2pWI9gWMWh8hP4WC9MupXiUAHo7YoliYcLXndt0DGHMFlI6LxQHCKYWjn6PNEDP0OEB1Vuj2oYuVP8u4KnY2Pv3JIxOFnP/5z3Cd2czLMFSjfJ5hh75GR7tsZFq4xJe9PWuYjpNoc44y2X81GCKqc/epC3yof5UDxwhtYEGBUSq3oJ9XxIMfnFlTu4f2PRN2eJTvA5Imtq8EkvCOc0L7V0QBrpMp64pSO7IMHXoEX5lR6POpvrAqkUvhxsTNyEE2lyPwjE1MFfV+Mj2ruQXU2c+MXrohsURynOs3NuOeDVwJr5MB67VWy6Ah2IODDQqxzltEeCzaqx2teK0ODNLi4
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-token
      namespace: cloudflared
