---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflared-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgCocwaUMHoYlv0euSEOvuKwZ1fxXrRuhJz6WLQLpToTUPI9tOxQfnM+gcVeGPg/qR3p5zhZ1fC0gYI0yUVJPIgYFvLjf01soXTfv4cHdPdWV75ENgpR/h4vLbw8zMuKIMaPBBXRpU7R+zwhRmNDD5LI7AeSq3nJr0BQOMurmSOWb8Pci9McjNWmbiXWE+hRrXdNKn7j3UURVglpRHjdpIrZkAy1dr6mQxCGq2Z9IHrpFKJVjPjC07Xf0h/4TRSKFfb46/ET1E7fIjhWp0Byif+9Oj80Au/ND/8GNs9KBEIr3Trgz1bbwJYCgWb+ObF8F+s2JmKvLYHvSjeWf8k06L3Wz0HfbcPE6LGnO7WwDy4+9L740vej6Blyk/gzqUMDsKKKwu8s7goI4dOiGHNqBvKZhiFNucXt+Pxc9XvsTSRuPHIlFkV83js+uHx6sMkc/fG11+1+VwtfkVwa9kHblEcc/HBL3Cums38QRy1vljl6Im0v2/GwznNkXuMrzJe0wHDALuZ8uAMuQrRhB1QpNVxEbS56XINpdfYQyteWtr8dKero6VKQKmDRpXd2KzgpaMgRoQSJ9R7DQACZQuM5PpNjtOyKNNnjIGxpXSj/xz3b98cNLp6hzswQ89bNkXzRIgeSCrTFXp+w3OwYb7C8Ubfu9uk5MZ8FBsY2YZukxqLWSd/XiZA7NYH4Cmj3J3N01RnvUZuPMa+zE03TLeUiumQLz1jQYDqScIszfMbgm+gmDl4VYvG06dzWTEMUt/ycGq42UckS3ffIrskx5TT7Re/qBWXpTe+E5+7GCkdiOFmY21BEg7GdibRNl2MVNEmozxkxUqBLykEeICaiw+6n9+eYm/rPUublhOJEhJDDdYZRKq0eAWHp21o07P66kz6YrNheCADTonDpCBU3ie/IahmD8hlhAJpwbno3VEjqphY2H/ji0BbLzVZI
  template:
    metadata:
      creationTimestamp: null
      name: cloudflared-token
      namespace: cloudflared
