apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: portfolio-db
  namespace: portfolio
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage:
    size: 5Gi
    storageClass: longhorn
  bootstrap:
    initdb:
      database: portfolio
      owner: portfolio