---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: minio-creds
  namespace: portfolio
spec:
  encryptedData:
    ACCESS_KEY: AgCtB7QCy97gOmfGP2tjw2icCClXCeUDWgoo/bJqL3EJM+M6YdnFv7a86/qLdAHcMyKcEE3tuP48d8rq8JI9QeDUUjrp4onwECZh+RPYe+fb/YVEK3A2sz1ytE2uDDcyLRB0w08ahgFGl0n5tOFHukd6f/AbdUY5RTBrzI0Rhno6aZqF3noc82A+jJ6fmRUU51elSNCfhlYP31re+I9cAhreW6vsAdzpzDG7IRKjYnEoGC78TXIeNpXO/kZ5Gf594OrGzIj79/mmLdEHUphx9Uk3nKtcQmTTvUqx2F43+t2WbjIKO+V1eztjqV5iTb9loS67aobEQPHQv/cyoUzS+oDAHpUVpRx/R7Da5FE1xR0dxPaOjvM+LZvlvT3FL0+jZfDz1FzTBWgu5GOrWiMvAx1kwbiYq2Dj5L/29yIMO3mg5o+Hh8bDon9SiglecszXY9gLBjKFB3CWsVse95mHpYn7iTYgoofyk+aOIdorw+4BMUEzdmwS6a62+ndmhcg8rlPDhH4P02q6H2uKfcnc2MIr9TSZeKsuCrVx1zebRR/4LVY3P88AVEHweIqZ9AMssL52uWAGatZ4sQOaCy9CqoZDxwv7Wqjs4a6eDIVSj6tTPbfKv6SPkPB76DUHhSy1Iglc9c4i8TEabN0YnE9Ei+WDyk8wzGG3gDdk9C4HfPQf08+tIjawMbDMce5EcLai5U+R36kRfrQfVA==
    SECRET_KEY: AgC/4d1r43iu3dr6PfCF+ozJQUng3+9HK89hGO3p4pEr2VCdZBh3S8Pk2dXOEEIf0rSyDskytUM7PuRRBZIlHX4Y+vTn5r2d4VsxJTl+fsoaqAn4XpjMb9P/ap8nitt9IQpxmxnUWwhKqNuQb0vpRhr6ZKyRVL0DXbQO6n4Lh5YOSjFpDHfD/DLU3trfRXQY8eqXt9w9krhmCPEZ5aES8E1iWjYPTjeKcT6XvhEzBF6hp58jZAWAMezSuJATslhMhCU53yFKq6pWQsoxUJHkhaVrMz2Z5LRAVvcN2NgUifE0i9tthHjuSZV866eqBb4N+KuD8krhXtHIYznzxeJMoL2Y2T+vp6RghdHCbVHA+F11iju9wtaFD2f52k5HV/7NVLHRJYxjir9Q5G0r27ff97rzhzdPlDj2tIzIIszLQBMEEvIgUYKM1Wn2CzDxrVwSs5jQypcQVIyRoSFLAmZUCzqLI/UIhWPu9cSnAJ76GjP+aQ2Zti3uXb1sUviAd2ALwn5uy/v14qlq0/0XcPQ7a6vH/lyuVJPAHXD4tIBzXLw6VCXQHvHAgp21cYT77I8E9FTjjr/OquHGoqE0v1l+SwZwrUq4wj6eJW1HqRUfy5mKtBw+bMJLM5nc9u+3ec9BDDGS/eYKHiB9mTmsEz3H8mYhvBBzy4AMq04JFdhtpWs0sLMO2V5pzDji/7EQltsHTW7ITi9dwr34s10jRqrkjzoVCshk/9DrRxQ33gGZazYxQ9adG/VsEaY0scOfXywUIyTn8ZM0Haywte1p+lHLg3w1
  template:
    metadata:
      creationTimestamp: null
      name: minio-creds
      namespace: portfolio
