apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  backupTargetURL: "nfs://192.168.1.248:/tank/backups/longhorn?nfsOptions=soft%2Ctimeo%3D330%2Cretrans%3D3%2Cretry%3D2"  
  pollInterval: 5m0s